import axios from "axios";

const axiosInstance = axios.create({
  baseURL: "https://guglu.ca/",
  headers: {
    "Content-Type": "application/json",
    Authorization:
      "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxMjk1IiwianRpIjoiYjBmMDY0ODhjMzY4ZjIwZmYxMzEwNmJhNzNlZDUzZTQ0ZDYzY2FjNDUzNTAwZWNiYTJhMGRlMWYzZTc5ZWZjNTAyZjZhYzk3YTkwYWZhYjYiLCJpYXQiOiIxNjc4ODcwNTAxLjc4NjE4MyIsIm5iZiI6IjE2Nzg4NzA1MDEuNzg2MTkwIiwiZXhwIjoiMTY3ODg3NDEwMS42MzIxNjAiLCJzdWIiOiIxMzA4Iiwic2NvcGVzIjpbXX0.XN5JCkg0HHLglXlUT_kS4sVwZaqDrUYQ-BhFAcuFukK6fFLz5mekn-NL2hmdexDt6dsz2uHkiVZMRmt0luFPL6gknLTSdZOx29Lyswv7ktyF9wkB9bQos74RbYGt2KLk3nghwddb1KUsz2VRjyq9biEr1TtUek3ot2XRpKZl1p2i3reDVE4EbsRoXA3PXx1c3WtBNEZ5teEEDPtyQAehJcIkB_zxNlflAH5fRdQYNJha0pyb_MBCe1oqbthAs2nW6TbMP2Tc8gHvJ_hnF-k8MdUAY_XGkdPtC6qxQ5OTQIg5UduWXck9VQoyiqa8JjBxVSk4XWHUjxrwiD5vq0dyExtJsThXRdtZKhSz5loxGFzKuVsmz9viRWXxPWBdMhYvhuZJFoURj60zn8DjEIMbOce5vt6pl37G3l6VD_cei17heTx-XgKSDjGGJoHxNNW7p3OPRYUWIXewXAWCq4cfNtdPGlKIQeowvt9Y3lJRXUWuRqazdw21YdAKcNX7ZjYFZ1qylKrjkVMOWGFbwnyUEp-mDByG8nvcjkUEYDIilrQs0nH680u2ixB4hBs2HUDuyBnyWhE5OVL-Lmqbl8LrTwPajrx-Tmas-NeQ0IZSHm3xeLHLYrdBv55_QxHswphRMc0IjeCurv-RDfj2V-JUbVBfS6SXdHp-6ZRdrk-ximQ",
  },
});

export default axiosInstance;
